= Part I: live CD -- installing -- pacstrap

This is the command that installs the most basic archlinux system.
You can also asks it to install other additional packages that you might
need in your future system, especially those which you'll need right away
when configuring it for the first time.

== List of useful packages to optionally install

    $ LIST="vim elinks ranger terminus-font"

elinks (new lynx) is especially needed incase your internet access requires to log in to some website
after rebooting to your new system.

== Install Arch linux on your new system in /mnt

EFI version:

    $ pacstrap /mnt base grub-efi-x86_64 efibootmgr $LIST

msdos/BIOS version:

    $ pacstrap /mnt base grub-bios $LIST

Total download+installation time for a 250kb/s internet connection: appr. 20-30min.

Edit: apparently doesn't work, $LIST doesn't get replaced as several arguments.
Is it a special behavior of zsh?
Alternative that seems to work:

    $ pacstrap /mnt base grub-bios `echo $LIST`

== Checking

    $ ls /mnt
