= Part II: first boot -- 1-check
:hardbreaks:

Check eveything is as you wanted. If some things aren't right, try to read next step 2-troubleshooting.

The first things you find out about are:
- grub menu entries
- root passwd
- keyboard layout
- console font

New system's root prompt will be symbolized with:

    r$ echo hello, world, i am root

Normal user prompt will be:

    u$ echo i am not root user

== GRUB: useful

to halt/reboot computer from grub: type 'c' to get command line mode, then type 'halt' or 'reboot' (US keyboard)


== FSTAB

what is mounted, where? including swap

    r$ lsblk
    r$ free --mega
    r$ swapon -s


== TIMEZONE, LOCALE, HOSTNAME

    r$ date          # what time is it?
    r$ locale
    r$ hostnamectl   # very useful command

    r$ timedatectl set-ntp true   # network time sync
    r$ timedatectl

if the output of timedatectl is correct (see 2-troubleshooting), use

    r$ hwclock --systohc

to copy the system clock onto the hardware clock (provided the system clock is valid) and to generate this file:

    r$ cat /etc/adjtime


== NETWORKING

    r$ elinks www.archlinux.org      # got the internet?
    r$ ip link                       # is <dev> UP?
    r$ pidof dhcpcd
    r$ systemctl status dhcpcd@<dev> # service active?
