= Part II: first boot -- 2-user

Create a new user, give it sudo powers


== NEW USER

    $ useradd -mU -G wheel,storage,power -s /bin/bash myuser

explanations:
[-m --create-home] create homedir
[-U --user-group] create a group with same name as user
alternative to [-U] : [-g users]
# 'users' group is the default choice for normal user accounts
[-G] other groups to add the user to

check

    $ grep myuser /etc/passwd /etc/group

give it a passwd

    $ passwd myuser

test password

    $ exit
    login: myuser

then get back as root for what follows.
note: if for example you put /bin/zsh as shell for myuser, but it's not installed yet, you get a failed login even with a good passwd, and no other clear evidence of what went wrong.
to gen better feedback regarding what might be wrong, try from the root prompt

    $ su myuser

to modify a user

    $ usermod -s /bin/bash myuser

the options are probably like those of useradd


== SUDO

as root:

    $ pacman -S sudo
    $ EDITOR=vi visudo    # if you don't have vim installed
    $ visudo     # if you have vim installed

uncomment

    %wheel ALL=(ALL) ALL

don't uncomment the similar line below it which contains NOPASSWD
now anyone in group wheel, like myuser, can use sudo powers
check

    $ [ctrl+D]
    login: myuser
    $ sudo echo it worked
