= Part II: first boot -- 2-user

Create a new user, give it sudo powers


== NEW USER

Let <user> be the name of the new normal user you'll create.

    r$ useradd -mU -G wheel,storage,power -s /bin/bash <user>

explanations:
[-m --create-home] create homedir
[-U --user-group] create a group with same name as <user>
alternative to [-U] : [-g users]
# 'users' group is the default choice for normal user accounts
[-G] other groups to add the user to

check

    r$ grep <user> /etc/passwd /etc/group

give it a passwd

    r$ passwd <user>

test password

    r$ exit
    login: <user>

then get back as root for what follows.
note: if for example you put /bin/zsh as shell for myuser, but it's not installed yet, you get a failed login even with a good passwd, and no other clear evidence of what went wrong.
to gen better feedback regarding what might be wrong, try from the root prompt

    r$ su <user>

To modify a user:

    r$ usermod -s /bin/bash <user>

The other options are probably like those of useradd


== SUDO

as root:

    r$ pacman -S sudo
    r$ EDITOR=vi visudo    # if you don't have vim installed
    r$ visudo     # if you have vim installed

uncomment

    %wheel ALL=(ALL) ALL

don't uncomment the similar line below it which contains NOPASSWD
now anyone in group wheel, like myuser, can use sudo powers
check

    r$ [ctrl+D]
    login: myuser
    u$ sudo echo it worked
