= Part I: live CD -- 1-start

You've booted into the Arch live CD and you're at the root prompt.
Fight troll [y/N]?

== Useful to know

To scroll up/down the console screen: shift + pageup, shift + pagedown
To switch to another console: alt + leftarrow, alt + rightarrow
/!\ Warning: switching to another console erases the scrolling history of the current console

== Setting up the environment

Keyboard layout
----
$ ls /usr/share/kbd/keymaps/**/*.map.gz
$ loadkeys fr
----
Check if you have an internet connection

    $ pacman -Sy
    $ ping www.archlinux.org # an alternative if you're not in a VM, also:
    $ wget -O >(cat) -o /dev/null www.archlinux.org | less

If you don't because of some website authentification page, use `elinks`

Better console font family

    $ pacman -S terminus-font
    $ pacman -Ql terminus-font    # list available fonts
    $ setfont ter-v24n

== Assessing

Bootloader: EFI/GPT or BIOS/msdos? check if the following path exists:

    $ ls /sys/firmware/efi/efivars

if not, your BIOS doesn't support EFI/GPT-based bootloading.

== Useful to have

    $ pacman -S vim          # probably already installed
    $ pacman -S ranger
    $ EDITOR=vim
