= Part I: live CD -- 2-partition

Using parted



== START

=== Useful to know

    (parted) help somecommand     # displays a lot of useful info

Incase you need to recuperate some lost partitions after a mistake

    $ pacman -S testdisk
    $ testdisk

=== Assessing

The disks and their partitions

    $ ls /dev/sd*     # what disks?
    $ fdisk -l /dev/sda      # what partitions already exist?
    $ blkid     # idem
    $ parted /dev/sda unit GiB print free     # idem

Enter the parted program, which then uses its own prompt

    $ parted /dev/sda
    (parted) unit MiB        # set up the default unit for display and input



== CREATE TABLE

This operation erases everything on the disk: all partitions previously there are deleted
Skip this step if you want to keep the partitions you may have currently on this disk

Execute either of those:

    (parted) mklabel gpt      # if you want a GPT disk table
    (parted) mklabel msdos    # if you want an msdos disk table

Checking

    (parted) print free



== BOOT PARTITION

Necessary if you're having the EFI/GPT flavor.
Create EFI sys partition (ESP) at the start of the disk.
Must be 550MiB in size.

    (parted) mkpart ESP fat32 1MiB 551MiB
    (parted) print free     # get the number of the new partition

Check the new partition (here number 1) is properly aligned

    (parted) align-check optimal 1

Set flags 'boot,esp' on that partition, to mark it as the EFI boot partition

    (parted) set 1 esp on



== OTHER PARTITIONS

=== To create a partition for the main filesystem '/'

If msdos: 'primary' for the three first, 'extended' for the last one,
'logical' for all the ones you put in the 'extended' one.
This to work around the fact that msdos tables don't handle more than 4
partitions on one disk.
If GPT: always 'primary' for as many partitions as you like.

    (parted) print free      # check out available and location of free space
    (parted) mkpart primary ext4 551MiB 19000MiB    # example
    (parted) print free      # get partition number, let's say 2

Checking

    (parted) align-check optimal 2

If BIOS/msdos:

    (parted) set 2 boot on    # make it bootable (here partition 2)
    (parted) print free       # Checking

=== To create a swap partition

Skip if one already exists somewhere else.
Best size: 50-150% of real RAM size.

    (parted) mkpart primary linux-swap 19000MiB 100%
    (parted) print free
    (parted) align-check optimal 1

Using percentages like 0% and 100% allows parted to choose the best alignment
for the start or end of a partition.

=== Quit parted

    (parted) quit



== FILESYSTEMS

=== Find partition numbers

Any of those

    $ fdisk -l /dev/sda      # what partitions already exist?
    $ blkid     # idem
    $ parted /dev/sda unit GiB print free     # idem

=== For the Boot partition

    $ mkfs.fat -F32 /dev/sda1

=== For any ext4 partition

    $ mkfs.ext4 /dev/sda2

=== For any swap partition

    $ mkswap -L <label> /dev/sda3

=== Name partitions

If GPT:

    $ parted /dev/sda name 2 myArchSys   # 2 is the partition number

If msdos, for ext2/ext3/ext4 partitions:

    $ e2label /dev/sda3 "myThirdPart"
    $ e2label /dev/sda4 "myFourthPart"

=== Checking

Same as always
