= Part I: live CD -- 3-install
:hardbreaks:

== MOUNTING

We must mount the partitions on which we'll install the new arch system, so they can be read and written on.

=== Mount the main filesystem '/' partition on the folder /mnt

    $ mount <root> /mnt
    $ mount -L {root} /mnt   # better alternative

=== If you have an EFI boot partition:

    $ mkdir /mnt/boot
    $ mount -L {boot} /mnt/boot

Check the efi flag of the boot partition: ok if this path exists

    $ ls /mnt/boot/EFI

=== Mount the swap partition

before installing:

    $ swapon <swap>
    $ swapon -L {swap}   # alternative with label

better safe than sorry, incase RAM gets limited (esp in a VM)

=== Check everything

    $ lsblk
    $ ls /mnt



== PACMAN

The installation of the new system in /mnt is going to download
all the required packages from the internet. So we have to get the best
mirrorlist possible.
/!\ archlinux .ORG -- not .COM!

    $ MLIST='www.archlinux.org/mirrorlist/?country=FR&protocol=http&protocol=https&ip_version=4'
    $ wget -O my-mirror-list "$MLIST"    # creates a new file called index?<stuff>
    $ head my-mirror-list     # check content
    $ mv my-mirror-list /etc/pacman.d/mirrorlist

Then uncomment some (all?) of the mirror links in the list:

    $ vim /etc/pacman.d/mirrorlist

or alternately:
----
    $ sed 's/^#//g' my-mirror-list > /etc/pacman.d/mirrorlist
----



== PACSTRAP

This is the command that installs the most basic archlinux system.
You can also asks it to install other additional packages that you might
need in your future system, especially those which you'll need right away
when configuring it for the first time.

=== Display options

To get total percentage of download progress during pacstrap installation, and a much prettier
display, uncomment the two lines:

    $ vim /etc/pacman.conf
    Color
    TotalDownload

=== List of useful packages to optionally install

    $ LIST="vim terminus-font ranger elinks lynx"

elinks and/or lynx are especially needed incase your internet access requires to log in to some website after rebooting to your new system. better have both if you're a little paranoid

=== Install Arch linux on your new system in /mnt

EFI version:

    $ pacstrap /mnt base grub-efi-x86_64 efibootmgr `echo $LIST`

msdos/BIOS version:

    $ pacstrap /mnt base grub-bios $LIST `echo $LIST`

Total download+installation time for a 250kb/s internet connection: appr. 20-30min.

=== Checking

    $ ls /mnt



== FSTAB

The command that generates the fstab file for the new system
is genfstab.

Before generating /mnt/etc/fstab, it may be useful to mount
all the partitions you'll want automatically mounted everytime
you'll boot onto your new system, in various mounting points
anywhere inside /mnt (which represents your future root '/' filesystem).

Especially, you'll want to swapon any swap partition you'll want automatically swapped on by your new system. If it is on when you use genfstab, it'll be added to /mnt/etc/fstab.

=== Generate /mnt/etc/fstab

    $ genfstab -Up /mnt >> /mnt/etc/fstab
    $ cat /mnt/etc/fstab   # check its content

Use -Lp instead of -Up if you want to use labels instead of UUIDs.

if you have to manually add a swap partition:

    $ vim /etc/fstab
    # <UUID> <mounting point> <fs> <options> <dump> <fsck>
    UUID=1234-5674  none      swap sw        0      0

=== Alternative: write it yourself

Fields are separated with whitespace (spaces or tabs)

File system: UUIDs or (PART)LABELs highly preferable

    UUID=0123456-789ABCDEF
    PARTLABEL={root}     # if GPT and named with parted
    LABEL={root}         # otherwise

Mount point:

    /           # for <root>
    /boot       # for <boot>
    none        # for <swap>
    /mnt/foo    # for the rest

Type:

    ext4        # foor ext4 partitions, esp <root>
    vfat        # for <boot> and other fat partitions
    swap        # for <swap>

Options:

    defaults,relatime  # good for most use cases, esp /
    sw                 # for swap partitions

Options generated by genfstab:

    rw,relatime        # genfstab for ext4 partitions
    defaults,pri=-2    # genfstab for swap partitions

Other options one might want to add to the comma-separated list:

    user,exec     # anyone can mount this partition
    nosuid        # deactivate suid (implied by user)
    nofail        # if sometimes the partition isn't there
    noauto        # don't automatically mount on startup

Note that the latter option also prevents `mount -a` from mounting that partition. That's probably what the system calls on startup anyway.

exec is added after user to override the implicit noexec that ships with the user option, and which would totally prevent anyone from executing any program stored in that partition.

Dump field: Always put a '0' for dump for every partition.

Fsck field: use '1' for fsck of <root>, and '2' for nearly any other partition, including <boot>. The exception being any swap partition, for which you'll want to put a '0'.

In the special case of the <boot> partition, it seems genfstab inserts a real big amount of options:

    rw,relatime,fmask=0022,dmask=0022,codepage=437,iocharset=iso8059-1,shortname=mixed,utf8,errors=remount-ro

You're probably better off leaving that to genfstab and adding stuff after it.
