= Part I: live CD -- partitioning -- create other partitions

== To create a partition for the main filesystem '/'

If msdos: 'primary' for the three first, 'extended' for the last one,
'logical' for all the ones you put in the 'extended' one.
This to work around the fact that msdos tables don't handle more than 4
partitions on one disk.
If GPT: always 'primary' for as many partitions as you like.

    (parted) print free      # check out available and location of free space
    (parted) mkpart primary ext4 551MiB 19000MiB    # example
    (parted) print free      # get partition number, let's say 2

Checking

    (parted) align-check optimal 2

If BIOS/msdos:

    (parted) set 2 boot on    # make it bootable (here partition 2)
    (parted) print free       # Checking

== To create a swap partition

Skip if one already exists somewhere else.
Best size: 50-150% of real RAM size.

    (parted) mkpart primary linux-swap 19000MiB 100%
    (parted) print free
    (parted) align-check optimal 1

Using percentages like 0% and 100% allows parted to choose the best alignment
for the start or end of a partition.

== Quit parted

    (parted) quit
